# Generated by Django 3.1.1 on 2020-10-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
