# Generated by Django 3.1.1 on 2020-10-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
    ]
