# Generated by Django 3.1.1 on 2020-10-04 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('posting', '0005_remove_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOfComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('comment_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
            options={
                'db_table': 'comment_of_comment',
            },
        ),
    ]
