# Generated by Django 3.1.1 on 2020-10-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20201014_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentofcomment',
            old_name='comment_of',
            new_name='comment',
        ),
    ]
