# Generated by Django 3.1.1 on 2020-10-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201004_0542'),
        ('posting', '0008_auto_20201014_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentofcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
